name: Deploy to EC2

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Execute SSH Command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/${{ secrets.SERVER_USERNAME }}/app/backend
          git pull origin dev
          docker-compose down
          docker-compose build
          docker-compose up -d
          docker image prune
